name: Renovate Config Validator

on:
  pull_request:
    paths:
      - "default.json"
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: "24"

      - name: Validate default.json
        run: npx --yes --package renovate -- renovate-config-validator default.json
